In [1]:
import numpy as np
from sklearn import preprocessing
input_data = np.random.uniform(-6.0,6.0, size=(4,3))
print(input_data)

[[-1.63425333 -3.73308274  2.48280994]
 [ 3.84810984 -4.30899244  1.9902286 ]
 [ 4.23703162 -1.96416953  3.97511094]
 [ 0.08645968 -4.66426678  3.34017212]]


In [2]:
# Lakukanlah binarization terhadap input_data dengan threshold 0.7

from sklearn.preprocessing import Binarizer

data_binarized = Binarizer(threshold = 0.7)
data_binarizer = data_binarized.transform(input_data)
print("Binarized data:\n", data_binarizer)

Binarized data:
 [[0. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]


In [3]:
# Lakukanlah scalling dengan kedua metode normalization terhadap input_data

from sklearn.preprocessing import MinMaxScaler, MaxAbsScaler

input_data = np.random.uniform(-6.0,6.0, size=(4,3))

scaler1 = MinMaxScaler()
scaled_data1 = scaler1.fit_transform(input_data)
print ("Min Max scaled data:\n", scaled_data1,'\n')

scaler2 = MaxAbsScaler()
scaled_data2 = scaler2.fit_transform(input_data)
print ("Max Abs scaled data:\n", scaled_data2,'\n')

Min Max scaled data:
 [[1.         0.         0.        ]
 [0.76008619 0.81668209 0.96259777]
 [0.         0.68850718 0.41576656]
 [0.89338601 1.         1.        ]] 

Max Abs scaled data:
 [[ 1.         -0.08065821 -0.40113131]
 [ 0.69707457  0.80189599  0.94759456]
 [-0.26264273  0.66338273  0.18141224]
 [ 0.86538462  1.          1.        ]] 



In [4]:
# Lakukanlah scaling dengan metode standardization terhadap input_data

from sklearn.preprocessing import StandardScaler
input_data = np.random.uniform(-6.0,6.0, size=(4,3))

std_data = StandardScaler()
scaler = std_data.fit_transform(input_data)
print ("Normalized data:\n", scaler)

Normalized data:
 [[-1.04919207 -0.58071154  1.2250662 ]
 [-0.44369963 -1.32479141 -0.58749602]
 [ 1.63750248  1.16749674  0.66884171]
 [-0.14461078  0.73800622 -1.30641189]]


In [5]:
import pandas as pd

df = pd.DataFrame({
    'name': ['J.A.R.V.I.S', 'WALL-E', 'Baymax', 'BB-8', 'Cortana'],
    'color': ['blue', 'brown', 'white', 'yellow', 'blue'],
    'type': ['live', 'cartoon', 'cartoon', 'live', 'cartoon' ]
    })
df

name   color     type
0  J.A.R.V.I.S    blue     live
1       WALL-E   brown  cartoon
2       Baymax   white  cartoon
3         BB-8  yellow     live
4      Cortana    blue  cartoon

In [8]:
# Lakukanlah label encoding terhadap kolom type

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['type_label'] = label_encoder.fit_transform(df['type'])
df

name   color     type       ...  type_label
0  J.A.R.V.I.S    blue     live  Ellipsis           1
1       WALL-E   brown  cartoon  Ellipsis           0
2       Baymax   white  cartoon  Ellipsis           0
3         BB-8  yellow     live  Ellipsis           1
4      Cortana    blue  cartoon  Ellipsis           0

In [9]:
# Lakukanlah one-hot encoding terhadap kolom type

from sklearn.preprocessing import OneHotEncoder

# One-Hot Encoding
onehot_encoder = OneHotEncoder()
onehot_encoded_type = onehot_encoder.fit_transform(df[['type']])
onehot_encoded_type_df = pd.DataFrame(onehot_encoded_type.toarray(), columns=onehot_encoder.get_feature_names(['type']))

# Concatenate DataFrame
df = pd.concat([df, onehot_encoded_type_df], axis=1)

# Print DataFrame
print(df)

          name   color     type       ...  type_label  type_cartoon  type_live
0  J.A.R.V.I.S    blue     live  Ellipsis           1           0.0        1.0
1       WALL-E   brown  cartoon  Ellipsis           0           1.0        0.0
2       Baymax   white  cartoon  Ellipsis           0           1.0        0.0
3         BB-8  yellow     live  Ellipsis           1           0.0        1.0
4      Cortana    blue  cartoon  Ellipsis           0           1.0        0.0


In [11]:
# Lakukanlah loading dataset iris

from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("First 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [12]:
# Lakukanlah splitting dataset

from sklearn.model_selection import train_test_split

# Split Dataset into Training Set and Test Set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [13]:
# Lakukanlah training model menggunakan algoritma KNN ( atau boleh juga mencoba dengan algoritma lain) dengan parameter neighbor bebas
# tampilkan juga akurasi dari model yang dihasilkan

from sklearn.neighbors import KNeighborsClassifier

n_neighbors = 3
classifier = KNeighborsClassifier(n_neighbors)
classifier.fit(X_train, y_train)

# Finding accuracy by comparing actual response values(y_test)with predicted response value(y_pred)
y_pred = classifier.predict(X_test)
accuracy = sum(y_pred == y_test) / len(y_test)
print("Accuracy:", accuracy)

# Providing sample data and the model will make prediction out of that data
sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = classifier.predict(sample)
pred_species = [iris.target_names[p] for p in preds] 
print("Predictions:", pred_species)

Accuracy: 1.0
Predictions: ['setosa', 'virginica']


In [20]:
# Simpanlah model yang telah di training sebelumnya menggunakan joblib

from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import joblib

# Save model using joblib
filename = 'knn_model.joblib'
joblib.dump(knn, filename)

print("['iris_classifier_knn.joblib']")

...

['iris_classifier_knn.joblib']


Ellipsis

In [ ]:
# Load model yang telah di save sebelumnya

...