1.	Buatlah 2 algoritma ensemble learning:  
        a.	Gunakan simple technique untuk kasus regresi menggunakan diabetes load_diabetes dataset dari sklearn. Kemudian carilah nilai RMSE, MAE, dan MAPE dari performa model ensemble learningnya.  
        b.	Gunakan advanced technique untuk melakukan klasifikasi pada dataset iris dari library sklearn. Kemudian buatlah dan tampilkan confusion matrix dari final modelnya  
        
        Notes: Bebas memilih menggunakan teknik ensemble learning manapun dan algotima manapun sebagai base dan final modelnya.


2. Lakukanlah 5-fold cross validation pada salah satu base model yang digunakan pada nomor 1.b

In [21]:
# Load diabetes dataset

from sklearn.datasets import load_diabetes

diabetes = load_diabetes(as_frame=True)
diabetes = diabetes.frame
diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [22]:
#1.a
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np

# Load dataset diabetes load_diabetes
diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

# Split data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Inisialisasi 3 model base
model1 = LinearRegression()
model2 = DecisionTreeRegressor(max_depth=3, random_state=0)
model3 = RandomForestRegressor(n_estimators=100, random_state=0)

# Training model base pada data latih
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

# Menggunakan metode voting untuk menggabungkan prediksi dari ketiga model
y_pred1 = model1.predict(X_test)
y_pred2 = model2.predict(X_test)
y_pred3 = model3.predict(X_test)
y_pred_ensemble = np.mean([y_pred1, y_pred2, y_pred3], axis=0)

# Evaluasi performa model ensemble learning menggunakan RMSE, MAE, dan MAPE pada data uji
rmse = np.sqrt(mean_squared_error(y_test, y_pred_ensemble))
mae = mean_absolute_error(y_test, y_pred_ensemble)
mape = np.mean(np.abs((y_test - y_pred_ensemble) / y_test)) * 100

print("RMSE: ", rmse)
print("MAE: ", mae)
print("MAPE: ", mape)


RMSE:  61.05993192171717
MAE:  48.18177639208153
MAPE:  39.28220078943887


In [23]:
# Load iris dataset

from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
iris = iris.frame
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [24]:
#1.b
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
import numpy as np

# Load dataset iris
iris = load_iris()
X = iris.data
y = iris.target

# Split data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Inisialisasi 3 model base
model1 = LogisticRegression(max_iter=1000, random_state=0)
model2 = RandomForestClassifier(n_estimators=100, random_state=0)
model3 = GradientBoostingClassifier(n_estimators=100, random_state=0)

# Training model base pada data latih
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

# Membuat dataset baru dari output ketiga model base pada data uji
pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)
pred_new = np.column_stack((pred1, pred2, pred3))

# Menggunakan model meta classifier untuk menggabungkan output dari ketiga model base
meta_model = LogisticRegression(max_iter=1000, random_state=0)
meta_model.fit(pred_new, y_test)

# Memprediksi label kelas pada data uji menggunakan ensemble learning dengan teknik stacking
y_pred = meta_model.predict(pred_new)

# Evaluasi performa model ensemble learning menggunakan confusion matrix pada data uji
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)


Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [25]:
#2
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

# Load dataset iris
iris = load_iris()
X = iris.data
y = iris.target

# Inisialisasi model base
model = RandomForestClassifier(n_estimators=100, random_state=0)

# Lakukan 5-fold cross validation pada model base
scores = cross_val_score(model, X, y, cv=5)

# Tampilkan nilai akurasi untuk setiap fold dan rata-rata akurasi
print("Accuracy Scores:", scores)
print("Mean Accuracy:", np.mean(scores))


Accuracy Scores: [0.96666667 0.96666667 0.93333333 0.96666667 1.        ]
Mean Accuracy: 0.9666666666666668
